name: synex
description: "Synex v1.0.0"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5

  suffadaemon:
    path: ../suffadaemon
  http: ^1.4.0
  shared_preferences: ^2.5.3
  bot_toast: ^4.1.3
  intl: ^0.20.2
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  emoji_picker_flutter: ^4.3.0
  signalr_netcore: ^1.4.3
  cached_network_image: ^3.4.1
  flutter_webrtc: 0.12.9
  permission_handler: ^12.0.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/synex.png
    - assets/images/user.png